'use client';
import {useEffect,useRef,useState} from 'react';
import {createChart,CandlestickSeries,LineSeries,HistogramSeries,AreaSeries,ColorType,createSeriesMarkers} from 'lightweight-charts';
import type {Bar,Trade,Drawing,DrawingKind,DrawingPoint} from '../lib/engine';
export type ChartLevel={id:string;price:number;kind:'entry'|'sl'|'tp';label:string;color:string;draft?:boolean;tradeId?:string;orderId?:string;editable:boolean;pending?:boolean};
export type PinePlot={name:string;style:string;overlay:boolean;color:string;width:number;indicatorId?:string;indicatorName?:string;data:{time:number;value:number|null;color?:string}[]};
export type PineShape={indicatorId:string;indicatorName:string;time:number;shape:string;location:string;color:string;text:string;textcolor:string;size:string};
export type PineDrawing={kind:'line'|'box'|'label'|'linefill';indicatorId:string;indicatorName:string;overlay?:boolean;[key:string]:any};
export type PineTable={indicatorId:string;indicatorName:string;position:string;columns:number;rows:number;cells:any[][];bgcolor?:string;frame_color?:string;frame_width?:number;border_color?:string;border_width?:number;[key:string]:any};
const dateFmt=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false});
const tickTime=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',hour12:false});
const tickDate=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',day:'2-digit',month:'short'});
const markerShape=(s:string)=>{const v=(s||'').toLowerCase();return v.includes('up')?'arrowUp':v.includes('down')?'arrowDown':v.includes('square')?'square':'circle'};
const markerPosition=(s:string)=>{const v=(s||'').toLowerCase();return v.includes('below')?'belowBar':v.includes('above')?'aboveBar':'inBar'};
const cssColor=(v:any,fallback='transparent')=>typeof v==='string'&&v&&v!=='na'?v:fallback;
function chartPreference(key:string){try{return localStorage.getItem(key)==='true';}catch{return false;}}
export default function ReplayChart({bars,trades,plots,shapes=[],pineDrawings=[],pineTables=[],barIndexOffset=0,onPrice,follow=true,drawings=[],drawingMode=null,onDrawing,levels=[],onLevelPreview,onLevelCommit,onDragStart,calculating=false,magnet=false,hiddenDrawings=false}:{bars:Bar[];trades:Trade[];plots:PinePlot[];shapes?:PineShape[];pineDrawings?:PineDrawing[];pineTables?:PineTable[];barIndexOffset?:number;follow?:boolean;onPrice?:(price:number)=>void;drawings?:Drawing[];drawingMode?:DrawingKind|null;onDrawing?:(drawing:Drawing)=>void;levels?:ChartLevel[];onLevelPreview?:(level:ChartLevel,price:number)=>void;onLevelCommit?:(level:ChartLevel,price:number)=>void;onDragStart?:()=>void;calculating?:boolean;magnet?:boolean;hiddenDrawings?:boolean}){
 const [expanded,setExpanded]=useState(false),[paneCount,setPaneCount]=useState(0),[focus,setFocus]=useState('draft');
 const [showPineText,setShowPineText]=useState(()=>chartPreference('xau-pine-text')),[showPineTables,setShowPineTables]=useState(()=>chartPreference('xau-pine-tables'));
 function toggleText(){setShowPineText(v=>{try{localStorage.setItem('xau-pine-text',String(!v));}catch{}return !v;});}
 function toggleTables(){setShowPineTables(v=>{try{localStorage.setItem('xau-pine-tables',String(!v));}catch{}return !v;});}
 const [preview,setPreview]=useState<{id:string;price:number}|null>(null);const activeDrag=useRef<{level:ChartLevel;price:number}|null>(null);const levelRef=useRef({levels,onLevelPreview,onLevelCommit,onDragStart,magnet});levelRef.current={levels,onLevelPreview,onLevelCommit,onDragStart,magnet};
 const host=useRef<HTMLDivElement>(null);const ref=useRef<any>(null);const onPriceRef=useRef(onPrice);onPriceRef.current=onPrice;const drawingRef=useRef(onDrawing);drawingRef.current=onDrawing;const drawingsRef=useRef({user:drawings,pine:pineDrawings});drawingsRef.current={user:drawings,pine:pineDrawings};const modeRef=useRef(drawingMode);modeRef.current=drawingMode;const draft=useRef<DrawingPoint|null>(null);const redrawFrame=useRef<number|undefined>(undefined);const [,setViewTick]=useState(0);
 useEffect(()=>{
  if(!host.current)return;
  const chart=createChart(host.current,{autoSize:true,layout:{background:{type:ColorType.Solid,color:'#10151d'},textColor:'#8f9caf',fontSize:12,fontFamily:"'Segoe UI',sans-serif",panes:{separatorColor:'#2b3442',separatorHoverColor:'#46546a',enableResize:true}},grid:{vertLines:{color:'#19212c'},horzLines:{color:'#19212c'}},crosshair:{mode:0,vertLine:{color:'#778495',labelBackgroundColor:'#344155'},horzLine:{color:'#778495',labelBackgroundColor:'#344155'}},timeScale:{timeVisible:true,secondsVisible:false,tickMarkFormatter:(t:any,type:number)=>{const d=typeof t==='number'?new Date(t*1000):new Date(Date.UTC(t.year,t.month-1,t.day));return type>=3?tickTime.format(d):tickDate.format(d)},borderColor:'#293241',rightOffset:8,barSpacing:7},rightPriceScale:{borderColor:'#293241',scaleMargins:{top:.12,bottom:.1}},localization:{priceFormatter:(v:number)=>v.toFixed(2),timeFormatter:(t:any)=>dateFmt.format(new Date(Number(t)*1000))}});
  const series=chart.addSeries(CandlestickSeries,{upColor:'#35c4a0',downColor:'#ef6b79',wickUpColor:'#35c4a0',wickDownColor:'#ef6b79',borderVisible:false,priceFormat:{type:'price',precision:2,minMove:.01}});
  const markers=createSeriesMarkers(series,[]);ref.current={chart,series,markers,lines:[],studies:new Map(),count:0};
  chart.subscribeClick((p:any)=>{if(!p.point||(p.paneIndex??0)!==0)return;let price=series.coordinateToPrice(p.point.y);if(price!==null&&levelRef.current.magnet){const ix=Math.round(chart.timeScale().coordinateToLogical(p.point.x)??-1),bar=ref.current?.data?.[ix];if(bar){const candidate=[bar.open,bar.high,bar.low,bar.close].sort((a:number,b:number)=>Math.abs(a-price!)-Math.abs(b-price!))[0];if(Math.abs((series.priceToCoordinate(candidate)??0)-p.point.y)<14)price=candidate;}}const time=chart.timeScale().coordinateToTime(p.point.x);if(price===null||time===null)return;const point={time:Number(time),price};const mode=modeRef.current;if(!mode){onPriceRef.current?.(price);return;}if(['hline','vline','text'].includes(mode)){drawingRef.current?.({id:crypto.randomUUID(),kind:mode,points:[point]});return;}if(!draft.current){draft.current=point;return;}drawingRef.current?.({id:crypto.randomUUID(),kind:mode,points:[draft.current,point]});draft.current=null;});
  const redraw=()=>{if((!drawingsRef.current.user.length&&!drawingsRef.current.pine.length&&!levelRef.current.levels.length)||redrawFrame.current!==undefined)return;redrawFrame.current=requestAnimationFrame(()=>{redrawFrame.current=undefined;setViewTick(v=>v+1)})};
  chart.timeScale().subscribeVisibleLogicalRangeChange(redraw);const el=host.current;el.addEventListener('wheel',redraw);el.addEventListener('pointermove',redraw);const observer=new ResizeObserver(redraw);observer.observe(el);
  return()=>{observer.disconnect();el.removeEventListener('wheel',redraw);el.removeEventListener('pointermove',redraw);chart.timeScale().unsubscribeVisibleLogicalRangeChange(redraw);if(redrawFrame.current!==undefined)cancelAnimationFrame(redrawFrame.current);ref.current=null;chart.remove()};
 },[]);
 useEffect(()=>{const r=ref.current;if(!r)return;r.data=bars;r.series.setData(bars as any);if(bars.length&&r.count===0)r.chart.timeScale().setVisibleLogicalRange({from:Math.max(0,bars.length-110),to:bars.length+8});else if(follow||bars.length<r.count)r.chart.timeScale().scrollToRealTime();r.count=bars.length;setViewTick(v=>v+1)},[bars,follow]);
 useEffect(()=>{const r=ref.current;if(!r)return;r.series.applyOptions({autoscaleInfoProvider:(base:Function)=>{const info=base();if(!info)return info;if(r.dragRange)return {...info,priceRange:r.dragRange};const selected=levels.some(l=>(l.tradeId||l.orderId||'draft')===focus)?focus:'draft';const prices=levels.filter(l=>(l.tradeId||l.orderId||'draft')===selected).map(l=>l.price).filter(p=>Number.isFinite(p)&&p>0);const range={minValue:Math.min(info.priceRange.minValue,...prices),maxValue:Math.max(info.priceRange.maxValue,...prices)};r.lastRange=range;return {...info,priceRange:range};}});setViewTick(v=>v+1)},[levels,focus]);
 useEffect(()=>{const r=ref.current;if(!r)return;for(const line of r.lines)r.series.removePriceLine(line);r.lines=[];
  const selected=levels.some(l=>(l.tradeId||l.orderId||'draft')===focus)?focus:'draft';
  for(const l of levels.filter(l=>(l.tradeId||l.orderId||'draft')===selected))r.lines.push(r.series.createPriceLine({price:preview?.id===l.id?preview.price:l.price,color:l.color,lineWidth:1,lineStyle:l.pending||l.draft?2:0,axisLabelVisible:true,title:l.label}));
  const markerData:any[]=[...trades.flatMap(t=>[{time:t.time,position:t.side==='long'?'belowBar':'aboveBar',color:t.side==='long'?'#35c4a0':'#ef6b79',shape:t.side==='long'?'arrowUp':'arrowDown',text:t.side==='long'?'Buy':'Sell'},...t.exits.map(e=>({time:e.time,position:'aboveBar',color:e.pnl>=0?'#35c4a0':'#ef6b79',shape:'circle',text:e.reason.split(' ')[0]}))]),...shapes.map(s=>({time:s.time,position:markerPosition(s.location),color:s.color,shape:markerShape(s.shape),text:showPineText?(s.text||s.indicatorName):''}))];
  const times=bars.map(b=>b.time);const mapped=markerData.map(m=>{let i=times.length-1;while(i>=0&&times[i]>m.time)i--;return i>=0?{...m,time:times[i]}:null}).filter(Boolean).sort((a:any,b:any)=>a.time-b.time);r.markers.setMarkers(mapped);
 },[trades,bars,shapes,levels,preview,focus,showPineText]);
 useEffect(()=>{const r=ref.current;if(!r)return;const live=new Set<string>();const panes=[...new Set(plots.filter(p=>!p.overlay).map(p=>p.indicatorId||'legacy'))];const previousPanes=r.chart.panes().length;
  for(const p of plots){const key=(p.indicatorId||'legacy')+'|'+p.name+'|'+p.style+'|'+(p.overlay?'1':'0');live.add(key);let s=r.studies.get(key);
   if(!s){const type=['style_histogram','style_columns'].includes(p.style)?HistogramSeries:p.style==='style_area'?AreaSeries:LineSeries;const c=typeof p.color==='string'?p.color:'#d7b46a';const options:any={title:p.name,color:c,lineColor:c,topColor:c,bottomColor:'#10151d00',lineWidth:p.width,priceLineVisible:false,lastValueVisible:true};if(type!==AreaSeries){delete options.topColor;delete options.bottomColor;delete options.lineColor;}s=r.chart.addSeries(type,options,p.overlay?0:panes.indexOf(p.indicatorId||'legacy')+1);r.studies.set(key,s);}
   s.moveToPane(p.overlay?0:panes.indexOf(p.indicatorId||'legacy')+1);s.applyOptions({color:p.color,lineWidth:p.width,lastValueVisible:false});s.setData(p.data.map(d=>d.value===null?{time:d.time}:{...d,value:d.value}));
  }
  for(const [key,s] of r.studies)if(!live.has(key)){if(calculating)s.setData([]);else{r.chart.removeSeries(s);r.studies.delete(key);}}
  if(r.chart.panes().length>previousPanes)for(let i=1;i<r.chart.panes().length;i++)r.chart.panes()[i].setHeight(150);
 setPaneCount(Math.max(0,r.chart.panes().length-1));setViewTick(v=>v+1);},[plots,calculating]);
 const overlay=(()=>{const r=ref.current;if(!r||!host.current)return null;const w=host.current.clientWidth,h=host.current.clientHeight;const xy=(p:DrawingPoint)=>[r.chart.timeScale().timeToCoordinate(p.time as any),r.series.priceToCoordinate(p.price)] as const;const pineX=(x:any,xloc:any)=>{const n=Number(x);if(!Number.isFinite(n))return null;const isTime=String(xloc||'').toLowerCase().includes('time')||String(xloc||'')==='bt';const t=isTime?Math.floor(n>1e12?n/1000:n):(bars[Math.trunc(n)-barIndexOffset]?.time);return t?r.chart.timeScale().timeToCoordinate(t as any):!isTime?r.chart.timeScale().logicalToCoordinate(n-barIndexOffset):null};const items:any[]=[];
  for(const d of hiddenDrawings?[]:drawings){const a=xy(d.points[0]);if(a[0]===null||a[1]===null)continue;if(d.kind==='vline'){items.push(<line key={'u'+d.id} x1={a[0]} x2={a[0]} y1={0} y2={r.chart.panes()[0].getHeight()} className="drawing-line"/>);continue;}if(d.kind==='text'){items.push(<text key={'u'+d.id} x={a[0]+4} y={a[1]-8} className="drawing-label">{d.text||'Note'}</text>);continue;}if(d.kind==='hline'){items.push(<line key={'u'+d.id} x1={0} x2={w} y1={a[1]} y2={a[1]} className="drawing-line"/>);continue;}const b=d.points[1]&&xy(d.points[1]);if(!b||b[0]===null||b[1]===null)continue;
   if(d.kind==='ray'){const far=w;const fy=a[1]+(b[1]-a[1])*(far-a[0])/(b[0]-a[0]||1);items.push(<line key={'u'+d.id} x1={a[0]} y1={a[1]} x2={far} y2={fy} className="drawing-line"/>);}if(d.kind==='ruler'||d.kind==='position'){const delta=d.points[1].price-d.points[0].price;items.push(<g key={'u'+d.id}><rect x={Math.min(a[0],b[0])} y={Math.min(a[1],b[1])} width={Math.max(1,Math.abs(b[0]-a[0]))} height={Math.max(1,Math.abs(b[1]-a[1]))} fill={delta>=0?'#35c4a022':'#ef6b7922'} stroke={delta>=0?'#35c4a0':'#ef6b79'}/><text x={Math.min(a[0],b[0])+6} y={Math.min(a[1],b[1])+15} className="drawing-label">{delta.toFixed(2)} USD · {(delta/d.points[0].price*100).toFixed(2)}% · {Math.round(Math.abs(d.points[1].time-d.points[0].time)/60)}m</text></g>);}if(d.kind==='trend')items.push(<line key={'u'+d.id} x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} className="drawing-line"/>);
   if(d.kind==='rect')items.push(<rect key={'u'+d.id} x={Math.min(a[0],b[0])} y={Math.min(a[1],b[1])} width={Math.abs(a[0]-b[0])} height={Math.abs(a[1]-b[1])} className="drawing-box"/>);
   if(d.kind==='fib'){const levels=[0,.236,.382,.5,.618,.786,1];items.push(<g key={'u'+d.id}>{levels.map(level=>{const y=a[1]+(b[1]-a[1])*level;return <g key={level}><line x1={Math.min(a[0],b[0])} x2={Math.max(a[0],b[0])} y1={y} y2={y} className="drawing-fib"/><text x={Math.max(a[0],b[0])+5} y={y-2} className="drawing-label">{Math.round(level*1000)/10}%</text></g>})}</g>);}
  }
  for(const d of [...pineDrawings.filter(d=>d.kind==='linefill'),...pineDrawings.filter(d=>d.kind!=='linefill')]){if(d.overlay===false)continue;
   if(d.kind==='linefill'&&d.line1&&d.line2&&!d.line1._deleted&&!d.line2._deleted){const points=[d.line1,d.line2].map(line=>{let ax=pineX(line.x1,line.xloc),bx=pineX(line.x2,line.xloc),ay=r.series.priceToCoordinate(Number(line.y1)),by=r.series.priceToCoordinate(Number(line.y2));if(ax===null||bx===null||ay===null||by===null)return null;const slope=(by-ay)/(bx-ax||1);if(['l','b','left','both'].includes(String(line.extend))){ay+=slope*(0-ax);ax=0;}if(['r','b','right','both'].includes(String(line.extend))){by+=slope*(w-bx);bx=w;}return [[ax,ay],[bx,by]];});if(points.every(Boolean)){const [a,b]=points as number[][][];items.push(<polygon key={'p-f-'+d.indicatorId+'-'+d.id} points={[...a,...b.slice().reverse()].map(p=>p.join(',')).join(' ')} fill={cssColor(d.color)}/>);}}

   if(d.kind==='line'){let x1=pineX(d.x1,d.xloc),x2=pineX(d.x2,d.xloc),y1=r.series.priceToCoordinate(Number(d.y1)),y2=r.series.priceToCoordinate(Number(d.y2));if(x1===null||x2===null||y1===null||y2===null)continue;const ax=x1,ay=y1,bx=x2,by=y2;const slope=(by-ay)/(bx-ax||1);if(['l','b','left','both'].includes(String(d.extend))){x1=0;y1=ay+slope*(x1-ax);}if(['r','b','right','both'].includes(String(d.extend))){x2=w;y2=ay+slope*(x2-ax);}items.push(<line key={'p-l-'+d.indicatorId+'-'+d.id} x1={x1} y1={y1} x2={x2} y2={y2} stroke={cssColor(d.color,'#d7b46a')} strokeWidth={Math.max(1,Number(d.width)||1)} strokeDasharray={['dashed','d'].includes(String(d.style))?'6 4':['dotted','o'].includes(String(d.style))?'2 4':undefined}/>);}
   if(d.kind==='box'){const x1=pineX(d.left,d.xloc),x2=pineX(d.right,d.xloc),y1=r.series.priceToCoordinate(Number(d.top)),y2=r.series.priceToCoordinate(Number(d.bottom));if(x1===null||x2===null||y1===null||y2===null)continue;items.push(<g key={'p-b-'+d.indicatorId+'-'+d.id}><rect x={Math.min(x1,x2)} y={Math.min(y1,y2)} width={Math.max(1,Math.abs(x2-x1))} height={Math.max(1,Math.abs(y2-y1))} fill={cssColor(d.bgcolor,'transparent')} stroke={cssColor(d.border_color,'transparent')} strokeWidth={Number(d.border_width)||1}/>{showPineText&&d.text&&<text x={Math.min(x1,x2)+4} y={Math.min(y1,y2)+14} fill={cssColor(d.text_color,'#dbe4ef')} fontSize="11">{d.text}</text>}</g>);}
   if(d.kind==='label'&&showPineText){const x=pineX(d.x,d.xloc),y=r.series.priceToCoordinate(Number(d.y));if(x===null||y===null)continue;items.push(<g key={'p-t-'+d.indicatorId+'-'+d.id}><rect x={x-3} y={y-14} width={Math.max(10,String(d.text||'').length*6+8)} height={18} rx={3} fill={cssColor(d.color,'#1d2835cc')}/><text x={x+1} y={y-2} fill={cssColor(d.textcolor,'#ffffff')} fontSize={String(d.size).includes('tiny')?9:String(d.size).includes('small')?10:12}>{d.text||''}</text></g>);}
  }
  return <svg className="drawing-overlay" width={w} height={h}><defs><clipPath id="pricePaneClip"><rect width={w} height={r.chart.panes()[0].getHeight()}/></clipPath></defs><g clipPath="url(#pricePaneClip)">{items}</g></svg>})();
 const priceAt=(clientY:number)=>{const r=ref.current;if(!r||!host.current)return null;const y=clientY-host.current.getBoundingClientRect().top;if(y<0||y>r.chart.panes()[0].getHeight())return null;const value=r.series.coordinateToPrice(y);return value===null?null:Math.round(value*100)/100;};
 const groups=[...new Set(levels.map(l=>l.tradeId||l.orderId||'draft'))];const handles=levels.filter(l=>(l.tradeId||l.orderId||'draft')===(groups.includes(focus)?focus:'draft')).map(l=>{const r=ref.current;if(!r)return null;const price=preview?.id===l.id?preview.price:l.price;const y=r.series.priceToCoordinate(price);if(y===null||y<0||y>r.chart.panes()[0].getHeight())return null;return <button key={l.id} className={'chart-price-handle '+l.kind+(l.pending?' pending-level':'')} style={{top:y-17,borderColor:l.color,color:l.color}} aria-label={l.label+' '+price.toFixed(2)+(l.editable?' ลากเพื่อปรับราคา':'')} disabled={!l.editable} onPointerDown={e=>{e.preventDefault();e.stopPropagation();levelRef.current.onDragStart?.();e.currentTarget.setPointerCapture(e.pointerId);if(ref.current?.lastRange)ref.current.dragRange={...ref.current.lastRange};activeDrag.current={level:l,price:l.price};setPreview({id:l.id,price:l.price});}} onPointerMove={e=>{if(!activeDrag.current||activeDrag.current.level.id!==l.id)return;const value=priceAt(e.clientY);if(value===null)return;activeDrag.current.price=value;setPreview({id:l.id,price:value});if(l.draft)levelRef.current.onLevelPreview?.(l,value);}} onPointerUp={e=>{if(!activeDrag.current)return;const drag=activeDrag.current;activeDrag.current=null;if(ref.current)ref.current.dragRange=null;e.currentTarget.releasePointerCapture(e.pointerId);setPreview(null);if(drag.price!==drag.level.price)levelRef.current.onLevelCommit?.(drag.level,drag.price);}} onPointerCancel={()=>{if(activeDrag.current?.level.draft)levelRef.current.onLevelPreview?.(activeDrag.current.level,activeDrag.current.level.price);activeDrag.current=null;if(ref.current)ref.current.dragRange=null;setPreview(null);}} onKeyDown={e=>{if(e.key==='Escape'){if(activeDrag.current?.level.draft)levelRef.current.onLevelPreview?.(activeDrag.current.level,activeDrag.current.level.price);activeDrag.current=null;if(ref.current)ref.current.dragRange=null;setPreview(null);}if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();levelRef.current.onDragStart?.();levelRef.current.onLevelCommit?.(l,Math.round((l.price+(e.key==='ArrowUp'?1:-1)*(e.shiftKey?1:.01))*100)/100);}}}><span>{l.label}</span><strong>{price.toFixed(2)}</strong>{l.editable&&<span className="handle-grip">⠿</span>}</button>;});
 async function exportChart(){const r=ref.current;if(!r)return;const canvas=r.chart.takeScreenshot();const ctx=canvas.getContext('2d');const svg=host.current?.parentElement?.querySelector('.drawing-overlay');if(ctx&&svg){const clone=svg.cloneNode(true) as SVGElement;clone.setAttribute('xmlns','http://www.w3.org/2000/svg');const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent='.drawing-line,.drawing-fib{stroke:#d7b46a;stroke-width:1.4}.drawing-box{fill:#d7b46a18;stroke:#d7b46a}.drawing-label{fill:#d7b46a;font:11px sans-serif}';clone.prepend(style);const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'}));try{const img=new Image();img.src=url;await img.decode();ctx.drawImage(img,0,0,canvas.width,canvas.height);}finally{URL.revokeObjectURL(url);}}canvas.toBlob((blob:Blob|null)=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='XAUUSD-replay.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);});}
 useEffect(()=>{const next=levels.filter(l=>l.tradeId).at(-1)?.tradeId;if(next)setFocus(next);},[trades.filter(t=>t.remaining>0).length]);
 const tableGroups=new Map<string,PineTable[]>();for(const t of (showPineTables?pineTables:[]).filter(t=>t.cells?.some(row=>row.some(cell=>cell?.text?.trim())))){const pos=String(t.position||'top_right').replaceAll('_','-');tableGroups.set(pos,[...(tableGroups.get(pos)||[]),t]);}
 const tables=[...tableGroups].map(([position,group])=><div key={position} className={'pine-table-group pine-table-'+position}>{group.map(t=><details open key={t.indicatorId+'-'+t.id} className="pine-table" style={{background:cssColor(t.bgcolor,'#10151de6'),borderColor:cssColor(t.frame_color||t.border_color,'#334155')}}><summary className="pine-table-name">{t.indicatorName}</summary><table><tbody>{(t.cells||[]).map((row:any[],ri:number)=><tr key={ri}>{row.map((cell:any,ci:number)=><td key={ci} style={{background:cssColor(cell?.bgcolor,'transparent'),color:cssColor(cell?.text_color,'#dbe4ef'),textAlign:(cell?.text_halign||'left').replace('text.align_','') as any}} title={cell?.tooltip||''}>{cell?.text||''}</td>)}</tr>)}</tbody></table></details>)}</div>);
 return <div className={'chart-stage'+(drawingMode?' drawing-active':'')+(expanded?' chart-expanded':'')}><div className="chart-view-tools"><select aria-label="เลือกออเดอร์ที่จะลากบนกราฟ" value={groups.includes(focus)?focus:'draft'} onChange={e=>setFocus(e.target.value)}>{groups.map(g=><option key={g} value={g}>{g==='draft'?'Draft SL / TP':(levels.find(l=>l.tradeId===g||l.orderId===g)?.label.split(' ').slice(0,2).join(' ')||g)}</option>)}</select><button onClick={()=>ref.current?.chart.timeScale().fitContent()} title="ดูช่วงที่เปิดแล้วทั้งหมด">Fit</button><button onClick={()=>ref.current?.chart.timeScale().setVisibleLogicalRange({from:Math.max(0,bars.length-110),to:bars.length+8})}>Reset</button><button onClick={()=>setExpanded(v=>!v)}>{expanded?'ย่อกราฟ':'ขยายกราฟ'}</button><button onClick={()=>void exportChart()}>PNG</button><button aria-pressed={showPineText} onClick={toggleText}>ข้อความอินดี้</button><button aria-pressed={showPineTables} onClick={toggleTables}>Dashboard</button></div><div className="chart-scroll-content" style={{height:Math.max(420,320+paneCount*150)}}><div className="chart-canvas" ref={host} aria-label="กราฟแท่งเทียน XAUUSD พร้อมอินดิเคเตอร์"/>{overlay}{handles}{tables}</div></div>;
}
